/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CallbackRouteImport } from './routes/callback'
import { Route as BuyTicketRouteImport } from './routes/buy-ticket'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TicketTicketIdRouteImport } from './routes/ticket.$ticketId'
import { Route as ApiStoreResultsRouteImport } from './routes/api/store-results'
import { Route as ApiNewRoundRouteImport } from './routes/api/new-round'
import { Route as ApiCloseRouteImport } from './routes/api/close'

const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyTicketRoute = BuyTicketRouteImport.update({
  id: '/buy-ticket',
  path: '/buy-ticket',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketTicketIdRoute = TicketTicketIdRouteImport.update({
  id: '/ticket/$ticketId',
  path: '/ticket/$ticketId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStoreResultsRoute = ApiStoreResultsRouteImport.update({
  id: '/api/store-results',
  path: '/api/store-results',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNewRoundRoute = ApiNewRoundRouteImport.update({
  id: '/api/new-round',
  path: '/api/new-round',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCloseRoute = ApiCloseRouteImport.update({
  id: '/api/close',
  path: '/api/close',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/buy-ticket': typeof BuyTicketRoute
  '/callback': typeof CallbackRoute
  '/api/close': typeof ApiCloseRoute
  '/api/new-round': typeof ApiNewRoundRoute
  '/api/store-results': typeof ApiStoreResultsRoute
  '/ticket/$ticketId': typeof TicketTicketIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/buy-ticket': typeof BuyTicketRoute
  '/callback': typeof CallbackRoute
  '/api/close': typeof ApiCloseRoute
  '/api/new-round': typeof ApiNewRoundRoute
  '/api/store-results': typeof ApiStoreResultsRoute
  '/ticket/$ticketId': typeof TicketTicketIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/buy-ticket': typeof BuyTicketRoute
  '/callback': typeof CallbackRoute
  '/api/close': typeof ApiCloseRoute
  '/api/new-round': typeof ApiNewRoundRoute
  '/api/store-results': typeof ApiStoreResultsRoute
  '/ticket/$ticketId': typeof TicketTicketIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/buy-ticket'
    | '/callback'
    | '/api/close'
    | '/api/new-round'
    | '/api/store-results'
    | '/ticket/$ticketId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/buy-ticket'
    | '/callback'
    | '/api/close'
    | '/api/new-round'
    | '/api/store-results'
    | '/ticket/$ticketId'
  id:
    | '__root__'
    | '/'
    | '/buy-ticket'
    | '/callback'
    | '/api/close'
    | '/api/new-round'
    | '/api/store-results'
    | '/ticket/$ticketId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuyTicketRoute: typeof BuyTicketRoute
  CallbackRoute: typeof CallbackRoute
  ApiCloseRoute: typeof ApiCloseRoute
  ApiNewRoundRoute: typeof ApiNewRoundRoute
  ApiStoreResultsRoute: typeof ApiStoreResultsRoute
  TicketTicketIdRoute: typeof TicketTicketIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buy-ticket': {
      id: '/buy-ticket'
      path: '/buy-ticket'
      fullPath: '/buy-ticket'
      preLoaderRoute: typeof BuyTicketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ticket/$ticketId': {
      id: '/ticket/$ticketId'
      path: '/ticket/$ticketId'
      fullPath: '/ticket/$ticketId'
      preLoaderRoute: typeof TicketTicketIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/store-results': {
      id: '/api/store-results'
      path: '/api/store-results'
      fullPath: '/api/store-results'
      preLoaderRoute: typeof ApiStoreResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/new-round': {
      id: '/api/new-round'
      path: '/api/new-round'
      fullPath: '/api/new-round'
      preLoaderRoute: typeof ApiNewRoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/close': {
      id: '/api/close'
      path: '/api/close'
      fullPath: '/api/close'
      preLoaderRoute: typeof ApiCloseRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuyTicketRoute: BuyTicketRoute,
  CallbackRoute: CallbackRoute,
  ApiCloseRoute: ApiCloseRoute,
  ApiNewRoundRoute: ApiNewRoundRoute,
  ApiStoreResultsRoute: ApiStoreResultsRoute,
  TicketTicketIdRoute: TicketTicketIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
