/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StoreResultsRouteImport } from './routes/store-results'
import { Route as NewRoundRouteImport } from './routes/new-round'
import { Route as CloseRouteImport } from './routes/close'
import { Route as CallbackRouteImport } from './routes/callback'
import { Route as BuyTicketRouteImport } from './routes/buy-ticket'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TicketTicketIdRouteImport } from './routes/ticket.$ticketId'

const StoreResultsRoute = StoreResultsRouteImport.update({
  id: '/store-results',
  path: '/store-results',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoundRoute = NewRoundRouteImport.update({
  id: '/new-round',
  path: '/new-round',
  getParentRoute: () => rootRouteImport,
} as any)
const CloseRoute = CloseRouteImport.update({
  id: '/close',
  path: '/close',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyTicketRoute = BuyTicketRouteImport.update({
  id: '/buy-ticket',
  path: '/buy-ticket',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TicketTicketIdRoute = TicketTicketIdRouteImport.update({
  id: '/ticket/$ticketId',
  path: '/ticket/$ticketId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/buy-ticket': typeof BuyTicketRoute
  '/callback': typeof CallbackRoute
  '/close': typeof CloseRoute
  '/new-round': typeof NewRoundRoute
  '/store-results': typeof StoreResultsRoute
  '/ticket/$ticketId': typeof TicketTicketIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/buy-ticket': typeof BuyTicketRoute
  '/callback': typeof CallbackRoute
  '/close': typeof CloseRoute
  '/new-round': typeof NewRoundRoute
  '/store-results': typeof StoreResultsRoute
  '/ticket/$ticketId': typeof TicketTicketIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/buy-ticket': typeof BuyTicketRoute
  '/callback': typeof CallbackRoute
  '/close': typeof CloseRoute
  '/new-round': typeof NewRoundRoute
  '/store-results': typeof StoreResultsRoute
  '/ticket/$ticketId': typeof TicketTicketIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/buy-ticket'
    | '/callback'
    | '/close'
    | '/new-round'
    | '/store-results'
    | '/ticket/$ticketId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/buy-ticket'
    | '/callback'
    | '/close'
    | '/new-round'
    | '/store-results'
    | '/ticket/$ticketId'
  id:
    | '__root__'
    | '/'
    | '/buy-ticket'
    | '/callback'
    | '/close'
    | '/new-round'
    | '/store-results'
    | '/ticket/$ticketId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuyTicketRoute: typeof BuyTicketRoute
  CallbackRoute: typeof CallbackRoute
  CloseRoute: typeof CloseRoute
  NewRoundRoute: typeof NewRoundRoute
  StoreResultsRoute: typeof StoreResultsRoute
  TicketTicketIdRoute: typeof TicketTicketIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/store-results': {
      id: '/store-results'
      path: '/store-results'
      fullPath: '/store-results'
      preLoaderRoute: typeof StoreResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-round': {
      id: '/new-round'
      path: '/new-round'
      fullPath: '/new-round'
      preLoaderRoute: typeof NewRoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/close': {
      id: '/close'
      path: '/close'
      fullPath: '/close'
      preLoaderRoute: typeof CloseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buy-ticket': {
      id: '/buy-ticket'
      path: '/buy-ticket'
      fullPath: '/buy-ticket'
      preLoaderRoute: typeof BuyTicketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ticket/$ticketId': {
      id: '/ticket/$ticketId'
      path: '/ticket/$ticketId'
      fullPath: '/ticket/$ticketId'
      preLoaderRoute: typeof TicketTicketIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuyTicketRoute: BuyTicketRoute,
  CallbackRoute: CallbackRoute,
  CloseRoute: CloseRoute,
  NewRoundRoute: NewRoundRoute,
  StoreResultsRoute: StoreResultsRoute,
  TicketTicketIdRoute: TicketTicketIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
